services:
  backend-postgres:
    image: "postgres:${BACKEND_POSTGRES_VERSION:-13}"
    container_name: backend-postgres
    environment:
      POSTGRES_USER: ${BACKEND_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BACKEND_POSTGRES_PASSWORD}
      POSTGRES_DB: ${BACKEND_POSTGRES_DB}
    volumes:
      - backend-postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${BACKEND_POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  backend:
    build:
      context: ./backend
    command: ["--host", "0.0.0.0", "--port", "80"]
    environment:
      SERVER_URL: ${SERVER_URL}
      KAKAO_REACTION_BLOCK_ID: ${KAKAO_REACTION_BLOCK_ID:-}
      MENU_DATA_DIR: /data/menus
      DATABASE_URL: postgresql://${BACKEND_POSTGRES_USER}:${BACKEND_POSTGRES_PASSWORD}@backend-postgres:5432/${BACKEND_POSTGRES_DB}
    ports:
      - "80:80"
    volumes:
      - ./backend/app:/code/app/
      - ./backend/tests:/code/tests/
      - ./data:/data/menus
    depends_on:
      backend-postgres:
        condition: service_healthy
    restart: always

volumes:
  backend-postgres-db-volume:
